export {
  palette,
  dashboardStyles,
  getPreviewContainer,
  getPreviewValue,
  getPreviewOpenBtn,
  getMetricPanel,
  getStatusDot,
  getStatusValue,
  getTrafficIconBox,
  getActivityPanel,
  getActivityIconBox,
  getActivityChip,
  getSummaryValue,
  onlineListRow,
  getFollowupTab,
} from './dashboard.styles';
