export const PERMISSIONS = {
  ACTIVITY: {
    VIEW: 'ACTIVITY_VIEW',
    ADD: 'ACTIVITY_ADD',
    EDIT: 'ACTIVITY_EDIT',
    DELETE: 'ACTIVITY_DELETE',
  },
  CUSTOMER: {
    VIEW: 'CUSTOMER_VIEW',
    ADD: 'CUSTOMER_ADD',
    EDIT: 'CUSTOMER_EDIT',
    DELETE: 'CUSTOMER_DELETE',
  },
  VEHICLE: {
    VIEW: 'VEHICLE_VIEW',
    ADD: 'VEHICLE_ADD',
    EDIT: 'VEHICLE_EDIT',
    DELETE: 'VEHICLE_DELETE',
  },
  REPORT: {
    VIEW: 'REPORT_VIEW',
    EXPORT: 'REPORT_EXPORT',
  },
  SETTINGS: {
    VIEW: 'SETTINGS_VIEW',
    MANAGE: 'SETTINGS_MANAGE',
  },
} as const;
